name: advent_of_code
description: Advent of Code 2022
version: 1.0.0

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  tuple: ^2.0.1
  collection: ^1.16.0
  quiver: ^3.1.0
  dijkstra: ^0.0.3
  equatable: ^2.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
